Vagrant.configure("2") do |config|

  ##############################
  #                            #
  #     Application server     #
  #                            #
  ##############################

  config.vm.define "app-server" do |app|
    app.vm.box = "debian/bullseye64"
    app.vm.box_version = "11.20241217.1"
    app.vm.hostname = "k3s-server"

    app.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
    end

    app.vm.network "public_network"
    app.vm.network "forwarded_port", guest: 2233, host: 2233, id: "ssh_custom"
    app.vm.network "forwarded_port", guest: 30443, host: 443, id: "https"
    app.vm.network "forwarded_port", guest: 30080, host: 80, id: "http"
    app.vm.disk :disk, size: "20GB", name: "storage"

    #setting root pw for the vm
    app.vm.provision "shell", run: "once", inline: <<-SHELL
      echo "root:Alma1234" | chpasswd
    SHELL

    #ansible setup
    app.vm.provision "shell", run: "once", inline: <<-SHELL
      apt-get update
      apt-get install -y ansible
    SHELL

    app.vm.synced_folder "../ansible", "/ansible"
    app.vm.synced_folder "../helm-charts", "/helm-charts"

    #setting up partitions for /opt and /tmp
    app.vm.provision "shell", run: "once", inline: <<-SHELL
      apt-get update
      apt-get install -y lvm2
      pvcreate /dev/sdb
      vgcreate vg_data /dev/sdb
      lvcreate -L 10G -n lv_opt vg_data
      lvcreate -L 10G -n lv_tmp vg_data
      mkfs.ext4 /dev/vg_data/lv_opt
      mkfs.ext4 /dev/vg_data/lv_tmp
      mount /dev/vg_data/lv_opt /opt
      mount /dev/vg_data/lv_tmp /tmp

      echo "/dev/vg_data/lv_opt /opt ext4 defaults 0 2" >> /etc/fstab
      echo "/dev/vg_data/lv_tmp /tmp ext4 defaults,nodev,nosuid,noexec 0 2" >> /etc/fstab

      chmod 1777 /tmp
    SHELL

    #feeding the vm with the playbook
    app.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/ansible/playbook.yaml"
      ansible.compatibility_mode = "2.0"
    end
  end

  #########################
  #                       #
  #     Jenkins server    #
  #                       #
  #########################

  config.vm.define "jenkins-server" do |jenkins|
    jenkins.vm.box = "debian/bullseye64"
    jenkins.vm.box_version = "11.20241217.1"
    jenkins.vm.hostname = "jenkins-server"

    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    jenkins.vm.network "public_network"
    jenkins.vm.network "forwarded_port", guest: 2233, host: 2234, id: "ssh_custom"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, id: "jenkins_web"

    #setting root pw for the vm
    jenkins.vm.provision "shell", run: "once", inline: <<-SHELL
      echo "root:Alma1234" | chpasswd
    SHELL

    #ansible setup
    jenkins.vm.provision "shell", run: "once", inline: <<-SHELL
      apt-get update
      apt-get install -y ansible
    SHELL

    jenkins.vm.synced_folder "../ansible", "/ansible"

    #feeding the vm with the jenkins playbook
    jenkins.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/ansible/jenkins-playbook.yaml"
      ansible.compatibility_mode = "2.0"
    end
  end

end